heat_template_version: 2014-10-16

description: >
  Extra hostname configuration


resources:

  ExtraConfig:
    type: OS::Heat::SoftwareConfig
    properties:
      group: script
      config: {get_file: /home/stack/templates/sriov-setup.sh}

  ExtraDeployments:
    type: OS::Heat::StructuredDeployments
    properties:
      #servers: {get_param: servers}
      config: {get_resource: ExtraConfig}
      actions: ['CREATE','UPDATE']
