---
- name: config selinux
  hosts: computes
  tasks:
    - selinux: policy=targeted state=permissive
    - service: name=NetworkManager.service state=stopped enabled=no

    - copy: src=sysfile/http.repo   dest=/etc/yum.repos.d/http.repo  
    - file: path=/etc/yum.repos.d/local.repo  state=absent #rm the file.
    - file: path=/etc/sysconfig/network-scripts/ifcfg-enp3s0f0  state=absent #rm the file.
    - file: path=/etc/sysconfig/network-scripts/ifcfg-enp3s0f1  state=absent #rm the file.

    - yum: name=ntp  state=present
    - yum: name=openstack-utils-2015.2-1.el7ost.noarch state=present

    - copy: src=sysfile/ntp.conf  dest=/etc/ntp.conf
    - service: name=ntpd  state=started enabled=yes

    - service: name=chronyd state=stopped enabled=no
 

    - name: config hugepage use 1G which is default in rhel7  and iommu
     #shell: sed -i '/GRUB_CMDLINE_LINUX/s/"$/ default_hugepagesz=1GB hugepagesz=1G hugepages=100"/g'  /etc/default/grub; grub2-mkconfig -o /boot/grub2/grub.cfg 
      lineinfile: dest=/etc/default/grub regexp=^GRUB_CMDLINE_LINUX=  line=GRUB_CMDLINE_LINUX="crashkernel=auto rd.lvm.lv=rhel/root rd.lvm.lv=rhel/swap rhgb quiet default_hugepagesz=1GB hugepagesz=1G hugepages=100 intel_iommu=on" 

    - name: apply above config
      shell: grub2-mkconfig -o /boot/grub2/grub.cfg

    - name: reboot for taking effect on hugepage configuration
      shell: sleep 2 && shutdown -r now "Ansible set hugepage triggered"
      async: 1
      poll: 0
      ignore_errors: true

    - name: waiting for server to come back within 420s  
      local_action: wait_for host={{ inventory_hostname }} state=started delay=10 timeout=420 port=22 

    - name: install package
      shell: yum -y  swap -- remove openvswitch -- install openvswitch-dpdk
     
    - name: config openvswitch 
#     lineinfile: dest=/etc/sysconfig/openvswitch insertafter=EOF line=DPDK_OPTIONS="-l 16-23 -n 1 --socket-mem 1024,0" state=present
#     appear ovs-ofctl hang issue
      lineinfile: dest=/etc/sysconfig/openvswitch insertafter=EOF line=DPDK_OPTIONS="-l 0,1 -n 1 --socket-mem 1024,1024" state=present
      tags: config-ovs
    
    - name: restart openvswitch service 
      service: name=openvswitch  state=restarted enabled=yes
    
    - name: waiting for server to come back within 60s  
      local_action: wait_for host={{ inventory_hostname }} state=started delay=10 timeout=60 port=22 
    
    - name: install dpdk 
      yum:  name={{item}}  state=present
      with_items:
          - dpdk
          - dpdk-tools
          - driverctl

    - name: load vfio_pci module 
      shell: modprobe vfio_pci 

    - name: bind intel interfaces to dpdk 
      shell: driverctl -v set-override {{item}} vfio-pci 
      with_items:
        - "0000:03:00.0"
        - "0000:03:00.1"
      ignore_errors: yes
      tags: bind-interface

    - name: config neutron 1 for ovs-dpdk 
      lineinfile: dest=/etc/neutron/plugins/ml2/openvswitch_agent.ini insertafter="#datapath_type" line=datapath_type=netdev state=present

    - name: config neutron 2 for ovs-dpdk 
      lineinfile: dest=/etc/neutron/plugins/ml2/openvswitch_agent.ini insertafter="#vhostuser_socket_dir" line=vhostuser_socket_dir=/var/run/openvswitch  state=present
 
    - name: restart neutron-openvswitch-agent 
      service: name=neutron-openvswitch-agent.service state=restarted

    - name: set bridge 
      shell: ovs-vsctl set bridge {{ item }} datapath_type=netdev
      with_items:
        - "br-phy1"
        - "br-phy2"
      ignore_errors: yes

    - name: add port to bridge
      shell: ovs-vsctl add-port {{item.bridge}} {{item.port}} -- set Interface {{item.port}} type=dpdk
      with_items:
        - {bridge: "br-phy1" , port: "dpdk0"}
        - {bridge: "br-phy2" , port: "dpdk1"}
      ignore_errors: yes

   
    - name: config nova for ovs-dpdk 
      lineinfile: dest=/etc/nova/nova.conf insertafter="#scheduler_default_filters" line=scheduler_default_filters=RamFilter,ComputeFilter,AvailabilityZoneFilter,ComputeCapabilitiesFilter,ImagePropertiesFilter,PciPassthroughFilter,NUMATopologyFilter  state=present
      
    - name: restart nova
      service: name=openstack-nova-compute.service  state=restarted

    - name: config openvswitch-nonetwork.service 1 
      lineinfile: dest=/usr/lib/systemd/system/openvswitch-nonetwork.service insertafter=EOF line=Group=qemu  state=present

    - name: config openvswitch-nonetwork.service 2 
      lineinfile: dest=/usr/lib/systemd/system/openvswitch-nonetwork.service insertafter=EOF line=UMask=0002  state=present
    
    - name: modify /usr/share/openvswitch/scripts/ovs-ctl
      copy: dest=/usr/share/openvswitch/scripts/ovs-ctl  src=sysfile/ovs-ctl 

    - name: config openvswitch_agent.ini
      lineinfile: dest=/etc/neutron/plugins/ml2/openvswitch_agent.ini insertafter="^bridge_mapping" line=bridge_mappings=phy1:br-phy1,phy2:br-phy2,phy3:br-phy3,phy4:br-phy4  state=present
    
    - name: reboot for taking effect on above configuration
      shell: sleep 2 && shutdown -r now "Ansible set ovs-dpdk triggered"
      async: 1
      poll: 0
      ignore_errors: true

    - name: waiting for server to come back within 420s  
      local_action: wait_for host={{ inventory_hostname }} state=started delay=10 timeout=420 port=22 
   

    
   
