heat_template_version: 2014-10-16

description: >
  This is a default no-op template which provides empty user-data
  which can be passed to the OS::Nova::Server resources.
  This template can be replaced with a different implementation via
  the resource registry, such that deployers may customize their
  first-boot configuration.

resources:
  userdata:
    type: OS::Heat::MultipartMime
    properties:
      parts:
      - config: {get_resource: repo_config}

  repo_config:
    type: OS::Heat::SoftwareConfig
    properties:
      group: script
      config: {get_file: /home/stack/templates/my-overcloud/firstboot/firstboot-setup.sh}


outputs:
  # This means get_resource from the parent template will get the userdata, see:
  # http://docs.openstack.org/developer/heat/template_guide/composition.html#making-your-template-resource-more-transparent
  # Note this is new-for-kilo, an alternative is returning a value then using
  # get_attr in the parent template instead.
  OS::stack_id:
    value: {get_resource: userdata}
